name: Deploy to Azure

on:
  push:
    branches:
      - GitHubActionsWorkFlow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: MoodPulseFuncApp  # 👈 This links the job to your GitHub environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish Azure Function
      uses: Azure/functions-action@v1
      with:
        app-name: moodpulsefuncapp
        package: ./MoodPulseFuncApp/bin/Release/net8.0/publish
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: Deploy App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: MoodPulseWebApp
        package: ./MoodPulseWebApp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
